services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Teddytrombone\IdeCompanion\:
    resource: "../Classes/*"

  Teddytrombone\IdeCompanion\Command\LspCommand:
    tags:
      - name: "console.command"
        command: "idecompanion:lsp"
        schedulable: false
        description: "Runs LSP server"
